
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# browser tags
windowrule = tag +browser, match:class ^(Brave-browser(-beta|-dev|-unstable)?)$
windowrule = tag +browser, match:class ^(zen-alpha|zen)$

# terminal tags
windowrule = tag +terminal, match:class ^(Alacritty|kitty|kitty-dropterm)$

# screenshare tags
windowrule = tag +screenshare, match:class ^(com.obsproject.Studio)$

# game tags
windowrule = match:class ^(gamescope)$, tag +games
windowrule = match:class ^(steam_app_\\d+)$, tag +games

# gamestore tags
windowrule = tag +gamestore, match:class ^([Ss]team)$
windowrule = tag +gamestore, match:title ^([Ll]utris)$
windowrule = tag +gamestore, match:class ^([Hh]eroic)$

# file-manager tags
windowrule = tag +file-manager, match:class ^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt|[Nn]emo)$

# multimedia-video tags
windowrule = tag +multimedia_video, match:class ^([Mm]pv|vlc)$

windowrule = float on, match:class (org.gnome.Calculator), match:title (Calculator)
windowrule = float on, match:class ^([Qq]alculate-gtk)$

# BLUR & FULLSCREEN
windowrule = no_blur on, match:tag games*
windowrule = fullscreen on, match:tag games*

#Float Rules
windowrule = match:class ^([Hh]eroic)$ match:title negative:(Heroic Games Launcher), float on
windowrule = match:class ^([Ss]team)$ match:title negative:^([Ss]team)$, float on


#Move to workspace
windowrule = workspace 1, match:tag browser*
windowrule = workspace 3, match:class ^(org\.qbittorrent\.qBittorrent)$
windowrule = workspace 4 silent, match:tag screenshare*
windowrule = workspace 5, match:tag gamestore*
windowrule = workspace 8, match:tag games*
windowrule = workspace 9 silent, match:tag multimedia*

windowrule = opacity 0.9 0.9, match:tag file-manager*
